targets:
  $default:
    builders:
      moor_generator:
        options:
          generate_connect_constructor: true

      source_gen|combining_builder:
        options:
          ignore_for_file:
            - unnecessary_this
            - return_of_invalid_type
            - constant_identifier_names
            - prefer_const_constructors_in_immutables
            - sort_unnamed_constructors_first
            - join_return_with_assignment