name: phenopod
description: Phenopods mobile client.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  equatable: ^1.1.1
  flutter_html: ^1.0.0
  flutter_bloc: ^4.0.0
  hydrated_bloc: ^4.0.0
  rxdart: ^0.24.0
  tailwind_colors: ^0.0.1
  timeago: ^2.0.26
  url_launcher: ^5.4.5
  cached_network_image: ^2.2.0+1
  audio_service: ^0.8.0
  just_audio: ^0.1.9
  intl: ^0.16.1
  modal_bottom_sheet: ^0.1.6+1
  page_transition: ^1.1.5
  uuid: ^2.0.4
  flutter_secure_storage: ^3.3.3
  device_info: ^0.4.2+4
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  path_provider: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
