name: phenopod
description: Phenopods mobile client.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.11.0
  cached_network_image: ^2.2.0+1
  cookie_jar: ^1.0.1
  copy_with_extension: ^1.2.0
  device_info: ^0.4.2+4
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  equatable: ^1.1.1
  flushbar: ^1.10.4
  flutter_html: ^1.0.0
  flutter_secure_storage: ^3.3.3
  google_fonts: ^1.1.0
  implicitly_animated_reorderable_list: ^0.2.3
  intl: ^0.16.1
  json_annotation: ^3.0.1
  just_audio: ^0.1.9
  logger: ^0.9.1
  modal_bottom_sheet: ^0.1.6+1
  moor: ^3.1.0
  moor_db_viewer: ^2.0.3
  moor_ffi: ^0.5.0
  retry: ^3.0.0+1
  rxdart: ^0.24.0
  seekbar: ^0.0.2
  share: ^0.6.4+3
  super_enum: ^0.4.2
  tailwind_colors: ^0.0.1
  timeago: ^2.0.26
  tuple: ^1.0.3
  url_launcher: ^5.4.5
  uuid: ^2.0.4
  page_transition: ^1.1.5
  path: ^1.6.4
  path_provider: ^1.6.10
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  copy_with_extension_gen: ^1.2.0
  json_serializable: ^3.3.0
  moor_generator: ^3.1.0
  pedantic: ^1.9.0
  super_enum_generator: ^0.5.0

flutter:
  uses-material-design: true
