name: piano
description: Phenopod mobile client.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  rxdart: ^0.24.0
  tailwind_colors: ^0.0.1
  timeago: ^2.0.26
  url_launcher: ^5.4.5
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
